### ISSUE TITLE
样式

### ISSUE THREAD

**Issue by 981128881** [cangshudada/vue-keyBoard#1]
可以自定义键盘的样式吗？

**Comment by cangshudada** [comment]
主题吗，目前暂时只支持配置主题色。目前自定义样式的话你可以fork代码自行修改

**Comment by cangshudada** [comment]
> 可以自定义键盘的样式吗？

主题吗，目前暂时只支持配置主题色。目前自定义样式的话你可以fork代码自行修改

**Comment by 981128881** [comment]
您好，谢谢答复，不只是样式，我想说的是例如切换到数字键盘，不想要字符，只要数字这种可以修改吗？谢谢

**Comment by cangshudada** [comment]
> 您好，谢谢答复，不只是样式，我想说的是例如切换到数字键盘，不想要字符，只要数字这种可以修改吗？谢谢

下个版本可以增加这个需求😄

**Comment by 981128881** [comment]
好的谢谢哦！
